export enum TabScreens {
  HOME = 'Home',
  MENU = 'Menu',
  ORDER = 'Order',
  FAVORITE = 'Favorite',
  NOTIFICATIONS = 'Notifications',
}

export enum Routes {
  FAQ = '/FAQ',
  ONBOARDING = '/',
  FILTER = '/filter',
  SIGN_IN = '/sign-in',
  SIGN_UP = '/sign-up',
  REVIEWS = '/reviews',
  CHECKOUT = '/checkout',
  MENU_ITEM = '/menu-item',
  MENU_LIST = '/menu-list',
  PROMOCODES = '/promocodes',
  EDIT_PROFILE = '/edit-profile',
  ORDER_FAILED = '/order-failed',
  NEW_PASSWORD = '/new-password',
  ORDER_HISTORY = '/order-history',
  TAB_NAVIGATOR = '/tab-navigator',
  LEAVE_A_REVIEW = '/leave-a-review',
  FORGOT_PASSWORD = '/forgot-password',
  ORDER_SUCCESSFUL = '/order-successful',
  PROMOCODES_EMPTY = '/promocodes-empty',
  TRACK_YOUR_ORDER = '/track-your-order',
  VERIFY_YOUR_EMAIL = '/verify-your-email',
  CONFIRMATION_CODE = '/confirmation-code',
  CREATE_PROFILE = '/sign-in/create-profile',
  ORDER_HISTORY_EMPTY = '/order-history-empty',
  SIGN_UP_ACCOUNT_CREATED = '/sign-up-account-created',
  VERIFY_YOUR_PHONE_NUMBER = '/verify-your-phone-number',
  FORGOT_PASSWORD_SENT_EMAIL = '/forgot-password-sent-email',
  SUPPORT_CENTER = '/support-center',
  CATEGORIES = '/categories',
  TOPUP_WALLET = '/topup-wallet',
}
